# Getting Familiar with TensorFlow

# Question 1 (2 points)

Import `TensorFlow`

In [3]:
import tensorflow as tf

# Question 2 (2 points)

Creates a `TensorFlow` constant with the values `[1, 2, 3]`. Print its shape and data type.

In [4]:
t = tf.constant([1,2,3])

print('Tensor shape is:', t.shape)
print('The data type of the tensor is:', t.dtype)

Tensor shape is: (3,)
The data type of the tensor is: <dtype: 'int32'>


# Question 3 (3 points)

Create two `TensorFlow` tensors of shape `(2, 3)` filled with random values, and add the two tensors element-wise.

In [5]:
import numpy as np

t1 = tf.constant(np.random.rand(2,3))
t2 = tf.constant(np.random.rand(2,3))

# adding the tensors
t3 = tf.add(t1,t2)

print('Tensor 1 is:', t1)
print('Tensor 2 is:', t2)
print('Tensor 3 is:', t3)

Tensor 1 is: tf.Tensor(
[[0.02541637 0.53203575 0.31883819]
 [0.57746734 0.01135793 0.80161307]], shape=(2, 3), dtype=float64)
Tensor 2 is: tf.Tensor(
[[0.05295835 0.29240135 0.3083015 ]
 [0.72653494 0.81535088 0.24757457]], shape=(2, 3), dtype=float64)
Tensor 3 is: tf.Tensor(
[[0.07837471 0.82443709 0.62713969]
 [1.30400228 0.82670881 1.04918764]], shape=(2, 3), dtype=float64)


# Question 4 (3 points)

Create a `TensorFlow` of shape `(4, 4)` filled with zeros and then change its value to 5.

In [10]:
t = tf.zeros(shape = (4,4))

print(t)

t = tf.constant(5, shape = (4,4))

print(t)

tf.Tensor(
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(4, 4), dtype=int32)


# Question 5 (3 points)

Create a tensor of shape `(2, 2)` filled with random values, multiply it by `4`, and print the result.

In [12]:
t = tf.constant(np.random.rand(2,2))

c = 4

t2 = c*t

print('Tensor is', t)
print('constant is', c)
print('c * Tensor is', t2)

Tensor is tf.Tensor(
[[0.57924319 0.86496482]
 [0.44415627 0.33869632]], shape=(2, 2), dtype=float64)
constant is 4
c * Tensor is tf.Tensor(
[[2.31697276 3.4598593 ]
 [1.7766251  1.35478529]], shape=(2, 2), dtype=float64)


# Question 6 (3 points)

Create two random tensors of shape `(1, 3)` and compute the dot product of the two tensors.

In [14]:
t1 = tf.constant(np.random.rand(1,3))
t2 = tf.constant(np.random.rand(1,3))

# compute dot product
dotp = tf.reduce_sum(tf.multiply(t1,t2))

print('Tensor 1 is', t1)
print('Tensor 2 is', t2)
print('Tensor 1 and 2 dot product is', dotp)


Tensor 1 is tf.Tensor([[0.13769547 0.77760788 0.94044622]], shape=(1, 3), dtype=float64)
Tensor 2 is tf.Tensor([[0.39919473 0.09044629 0.26126851]], shape=(1, 3), dtype=float64)
Tensor 1 and 2 dot product is tf.Tensor(0.3710080318391082, shape=(), dtype=float64)
